- hosts: lbservers
  roles:
    - lbserver

- hosts: webservers
  roles:
    - webserver

- hosts: databases
  roles:
    - database

- hosts: jenkins_controller
  roles:
    - jenkins_controller

- hosts: pipeline_agents
  roles:
    - jenkins_agents
