- name: install jenkins prerequisite
  ansible.builtin.apt:
    name: fontconfig
    update_cache: yes

- name: copy java sdk
  ansible.builtin.copy:
    src: OpenJDK11U-jdk_x64_linux_hotspot_11.0.17_8.tar.gz
    dest: /usr/lcoal/java/

- name: copy jenkins binary
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/vagrant/
    mode: '777'
  loop:
    - jenkins.war
    - jdk_installation.sh

- name: install java for jenkins controller
  ansible.builtin.shell: ./jdk_installation.sh
  args:
    chdir: /home/vagrant

# - name: start jenkins
#   ansible.builtin.shell:
#     cmd: java -jar jenkins.war -httpPort=8080
#     chidr: /home/vagrant

- name: copy ssh keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/vagrant/.ssh
  loop:
    - jenkins_agent_key
    - jenkins_agent_key.pub

- name: ssh keyscan
  ansible.builtin.shell: ssh-keyscan -H 192.168.12.21 >> /home/vagrant/.ssh/known_hosts
